/**
 * Compliance Checklist Catalog (module-wise)
 * Professional neutral source list for bootstrap template generation.
 */

export const COMPLIANCE_CHECKLIST_CATALOG = [
  { module: 'Finance', title: 'Invoice Approval Process', category: 'Invoices' },
  { module: 'Finance', title: 'Payment Approval', category: 'Payments' },
  { module: 'Finance', title: 'Approval to Sweep Funds', category: 'Workflows' },
  { module: 'Finance', title: 'Cash Handling Process', category: 'Cash Mgmt' },
  { module: 'Finance', title: 'Bank Card Usage', category: 'Cards' },
  { module: 'Finance', title: 'Refund Request Process', category: 'Refunds' },
  { module: 'Finance', title: 'Acquittal Refunds', category: 'Acquittals' },
  { module: 'Finance', title: 'Month-End Process', category: 'Period Close' },
  { module: 'Finance', title: 'Year-End Process', category: 'Period Close' },
  { module: 'Finance', title: 'BAS Lodgement', category: 'BAS' },
  { module: 'Finance', title: 'Accounting Software Maintenance', category: 'IT' },
  { module: 'Finance', title: 'Accounting Period Closure', category: 'Period Close' },
  { module: 'Finance', title: 'Bank & Platform Access Auth', category: 'Access' },
  { module: 'Finance', title: 'Financial Record-Keeping', category: 'Records' },
  { module: 'Finance', title: 'Emergency Financial Situations', category: 'Emergency' },
  { module: 'Finance', title: 'Emergency Financial Response Team', category: 'Emergency' },
  { module: 'Finance', title: 'Emergency Financial Procedures', category: 'Emergency' },
  { module: 'Finance', title: 'Emergency Financial Plan Activation', category: 'Emergency' },

  { module: 'Operations', title: 'Operational Procedures Policy', category: 'Policies' },
  { module: 'Operations', title: 'Operational Record Keeping', category: 'Records' },
  { module: 'Operations', title: 'Record-Keeping Operations', category: 'Records' },
  { module: 'Operations', title: 'Funding Agreement Management', category: 'Funding' },
  { module: 'International', title: 'FIP Identification & Engagement', category: 'FIPs' },
  { module: 'Operations', title: 'Project Identification', category: 'Projects' },
  { module: 'Operations', title: 'Allocation of Funding', category: 'Budgets' },
  { module: 'International', title: 'Engaging Field Partners', category: 'FIPs' },
  { module: 'Operations', title: 'Project Delivery & Review', category: 'Projects' },
  { module: 'Finance', title: 'Financial Acquittal Report', category: 'Acquittals' },
  { module: 'Operations', title: 'Project Delivery Evidence', category: 'Projects' },
  { module: 'International', title: 'FIP Records & Reviews', category: 'FIPs' },
  { module: 'International', title: 'FIP Registration', category: 'FIPs' },
  { module: 'International', title: 'Due Diligence & Screening', category: 'Due Diligence' },
  { module: 'Operations', title: 'Weekly Stats Reporting & Record Keeping', category: 'Reports' },
  { module: 'Operations', title: 'Non-conformance & Complaints Mgmt', category: 'Complaints' },
  { module: 'Operations', title: 'Live Complaints Management Tracker', category: 'Complaints' },

  { module: 'Compliance', title: 'Submission of AIS to ACNC', category: 'AIS' },
  { module: 'Compliance', title: 'Compliance, Audits & Reporting', category: 'Audits' },
  { module: 'Compliance', title: 'Compliance, Audits & Reporting (2)', category: 'Audits' },
  { module: 'Compliance', title: 'Compliance Reporting Policy', category: 'Policies' },
  { module: 'Compliance', title: 'General Reporting Policy', category: 'Reports' },
  { module: 'Compliance', title: 'Internal Auditing Policy', category: 'Audits' },
  { module: 'Compliance', title: 'Whistleblowing Policy', category: 'Governance' },
  { module: 'Compliance', title: 'Record Keeping & Duty to Notify', category: 'Records' },
  { module: 'Compliance', title: 'Annual Report Preparation', category: 'Reports' },
  { module: 'Compliance', title: 'External Auditor User Access', category: 'Audits' },
  { module: 'Compliance', title: 'Completed Records Policy', category: 'Records' },
  { module: 'Compliance', title: 'Anti-Financial Fraud, CTF & AML', category: 'AML/CTF' },
  { module: 'Compliance', title: 'Fundraising Policy', category: 'Fundraising' },

  { module: 'Marketing', title: 'Marketing Procedures', category: 'Procedures' },
  { module: 'Marketing', title: 'Social Media Access & Details', category: 'Social Media' },
  { module: 'Marketing', title: 'Social Media Access & Details (2)', category: 'Social Media' },
  { module: 'Marketing', title: 'Marketing Compliance Resources', category: 'Resources' },
  { module: 'Marketing', title: 'Marketing Training Resources & Records', category: 'Training' },
  { module: 'Marketing', title: 'Weekly Marketing Reporting', category: 'Reports' },
  { module: 'Marketing', title: 'Social Media Compliance', category: 'Social Media' },
  { module: 'Marketing', title: 'Marketing Performance Review', category: 'Reviews' },
  { module: 'Donor Care', title: 'Donor Care — Live Agent Checklist', category: 'Agents' },
  { module: 'Donor Care', title: 'Donor Care — Training', category: 'Training' },
  { module: 'Donor Care', title: 'VIP Donor Care', category: 'VIP' },
  { module: 'Donor Care', title: 'Donor Care — Refund/Complaints', category: 'Complaints' },

  { module: 'HR', title: 'Volunteer Engagement', category: 'Volunteers' },
  { module: 'HR', title: 'Volunteer Engagement Policy', category: 'Policies' },
  { module: 'HR', title: 'Volunteer Training Guidelines', category: 'Training' },
  { module: 'HR', title: 'Volunteer Register Policies', category: 'Register' },
  { module: 'HR', title: 'Weekly Stats Reporting Template', category: 'Reports' },
  { module: 'HR', title: 'Equal Employment Opportunity', category: 'Policies' },
  { module: 'HR', title: 'Health and Safety Policy', category: 'Safety' },
  { module: 'HR', title: 'Child Protection Policy', category: 'Safeguarding' },
  { module: 'HR', title: 'Safeguarding & Code of Conduct', category: 'Safeguarding' },
  { module: 'HR', title: 'Training for Staff, FIPs & Visitors', category: 'Training' },

  { module: 'Community', title: 'Community Sponsorship', category: 'Sponsorships' },
  { module: 'Community', title: 'Sponsorship Register & Tracker', category: 'Register' },
  { module: 'Community', title: 'Ad Hoc Sponsorship Reporting', category: 'Reports' },
  { module: 'Community', title: 'Community Sponsorship Register', category: 'Register' },
  { module: 'Community', title: 'Sponsorship Volunteer Training Records', category: 'Training' },
  { module: 'Donations', title: 'Donation Box Coordination', category: 'Boxes' },
  { module: 'Donations', title: 'Donation Box Register', category: 'Register' },
  { module: 'Donations', title: 'Donation Box Management', category: 'Boxes' },
  { module: 'Donations', title: 'Weekly Donation Box Stats', category: 'Reports' },

  { module: 'IT', title: 'Logins, Passwords & Access Control', category: 'Access' },
  { module: 'IT', title: 'Website Policy', category: 'Web' },
  { module: 'IT', title: 'Backup of Software', category: 'Backups' },
  { module: 'IT', title: 'Backup Plan for Field Partners', category: 'FIP Backups' },
  { module: 'IT', title: 'Disaster Recovery & BCP', category: 'DR/BCP' },
  { module: 'Insurance', title: 'Insurance for Ambassadors', category: 'Ambassadors' },
  { module: 'Insurance', title: 'Insurance, Systems, Permits & Legal', category: 'General' },
  { module: 'Governance', title: 'Licenses & Fundraising Permits', category: 'Licences' },
  { module: 'IT', title: 'Communication & Emergency Services Plan', category: 'Emergency' },
  { module: 'Governance', title: 'Board of Directors', category: 'Board' },
  { module: 'Governance', title: 'Declaration of Interest (COI)', category: 'COI' },
  { module: 'Governance', title: 'Suitability of Responsible Persons', category: 'Responsible Persons' },
  { module: 'Governance', title: 'Succession Plan for Key Persons', category: 'Succession' },
  { module: 'Governance', title: 'Constitution & By-laws', category: 'Constitution' },
  { module: 'Governance', title: 'Staff & Volunteer Conflict of Interest', category: 'COI' }
];

export const CHECKLIST_CATALOG_STATS = {
  total: 94,
  supersededBy: 'checklistLibraryV3.js',
  note: 'v1 catalog kept for backward compatibility. Use POST /templates/bootstrap-v3 for the optimised 50-checklist library.',
  modules: {
    Finance: 18,
    Operations: 17,
    Compliance: 13,
    Marketing: 12,
    HR: 10,
    Community: 9,
    IT_Insurance: 9,
    Governance: 6
  }
};

